# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import math_service_pb2 as math__service__pb2


class MathStub(object):
    """Provides information about the gRPC server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSquare = channel.unary_unary(
                '/Math/GetSquare',
                request_serializer=math__service__pb2.GetSquareRequest.SerializeToString,
                response_deserializer=math__service__pb2.GetSquareResponse.FromString,
                )


class MathServicer(object):
    """Provides information about the gRPC server.
    """

    def GetSquare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MathServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSquare': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSquare,
                    request_deserializer=math__service__pb2.GetSquareRequest.FromString,
                    response_serializer=math__service__pb2.GetSquareResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Math', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Math(object):
    """Provides information about the gRPC server.
    """

    @staticmethod
    def GetSquare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Math/GetSquare',
            math__service__pb2.GetSquareRequest.SerializeToString,
            math__service__pb2.GetSquareResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
